sudo: required
services:
  - docker

before_install:
  - docker build -t engsupport/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true engsupport/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "aLuistheGuru"
  env: " Aluistheguru-env"
  bucket_name: "elasticbeanstalk-us-east-1-175640507474"
  bucket_path: "aLuistheGuru"
  on:
    branch: master
      access_key_id: "$AWS_ACCESS_KEY"
      secret_access_key: "$AWS_SECRET_KEY"